// Required for WGPU backend due to complex type nesting
#![recursion_limit = "256"]

pub mod arrow_reader;
pub mod batching;
pub mod blt_core;
pub mod dataset;
pub mod dataset_helpers;
pub mod ffmpeg;
pub mod generic_processor;
pub mod hf_resolver;
pub mod huggingface_loader;
pub mod model;
pub mod modalities;
pub mod output;
pub mod patcher;
pub mod polars_dataset_loader;
pub mod polars_ext;
pub mod prefetch;
pub mod pretokenize;
pub mod quantization;
pub mod reference_sources;
pub mod sidecar;
pub mod sphere_ebm;
pub mod tokenizer;

/// Build-time information (git hash, build time, features).
/// Generated by the `built` crate during compilation.
pub mod built_info {
    include!(concat!(env!("OUT_DIR"), "/built.rs"));
}

/// Fused CubeCL operations for optimized GPU kernels.
///
/// Enabled by default when the `fused-entropy` feature is active. These kernels
/// fuse multiple steps (e.g., softmax + reduction) into single launches to reduce
/// memory traffic and kernel launch overhead. Disable with `--no-default-features`
/// if you prefer the reference implementations.
#[cfg(feature = "fused-entropy")]
pub mod fused_ops;
