// Required for WGPU backend due to complex type nesting
#![recursion_limit = "256"]

// Clippy pedantic allows - verified needed 2024-12-01
#![allow(clippy::doc_markdown)] // 247 instances - technical terms (BLT, WGPU, etc.)
#![allow(clippy::must_use_candidate)] // 70 instances - getters don't all need #[must_use]
#![allow(clippy::cast_possible_truncation)] // 66 instances - usize→i32 in tensor ops
#![allow(clippy::cast_precision_loss)] // 61 instances - usize→f32 acceptable in ML
#![allow(clippy::cast_sign_loss)] // 40 instances - handled carefully
#![allow(clippy::cast_possible_wrap)] // 26 instances - handled carefully
#![allow(clippy::similar_names)] // intentional variable naming
#![allow(clippy::too_many_arguments)] // complex processing functions
#![allow(clippy::missing_errors_doc)] // 102 instances - error docs low priority
#![allow(clippy::redundant_closure_for_method_calls)] // 21 instances - closures often clearer
#![allow(clippy::trivially_copy_pass_by_ref)] // 26 instances - &usize in APIs is fine
#![allow(clippy::cast_lossless)] // 25 instances - f32→f64, u8→i32 are intentional
#![allow(clippy::items_after_statements)] // 6 instances - local helpers after setup
#![allow(clippy::unused_self)] // 6 instances - trait consistency
#![allow(clippy::too_many_lines)] // 8 instances - complex functions
#![allow(clippy::case_sensitive_file_extension_comparisons)] // false positive - we use .to_lowercase()
#![allow(clippy::unnecessary_wraps)] // some functions may error in future
#![allow(clippy::single_match_else)] // match is often clearer than if-let-else

pub mod arrow_reader;
pub mod batching;
pub mod blt_core;
pub mod buffered_corpus;
pub mod corpus_db;
pub use corpus_db::RootsTreeNode; // H-ROOTS tree serialization for CorpusDB
pub mod dataset;
pub mod dataset_helpers;
pub mod ffmpeg;
pub mod generic_processor;
pub mod hf_resolver;
pub mod huggingface_loader;
// Incremental sphere optimization moved to sphere-pipeline crate
// (blt-burn provides storage via CorpusDB, sphere-pipeline orchestrates)
pub mod modalities;
pub mod model;
pub mod model_loader;
pub mod output;
pub mod patcher;
pub mod pipeline;
pub mod polars_dataset_loader;
pub mod polars_ext;
pub mod prefetch;
pub mod pretokenize;
pub mod quantization;
pub mod reference_sources;
pub mod sidecar;
pub mod tokenizer;

/// Build-time information (git hash, build time, features).
/// Generated by the `built` crate during compilation.
#[allow(clippy::needless_raw_string_hashes)] // generated code
pub mod built_info {
    include!(concat!(env!("OUT_DIR"), "/built.rs"));
}

/// Fused CubeCL operations for optimized GPU kernels.
///
/// Enabled by default when the `fused-entropy` feature is active. These kernels
/// fuse multiple steps (e.g., softmax + reduction) into single launches to reduce
/// memory traffic and kernel launch overhead. Disable with `--no-default-features`
/// if you prefer the reference implementations.
#[cfg(feature = "fused-entropy")]
pub mod fused_ops;
