pub mod arrow_reader;
pub mod batching;
pub mod blt_core;
pub mod dataset;
pub mod dataset_helpers;
pub mod ffmpeg;
pub mod generic_processor;
pub mod huggingface_loader;
pub mod model;
pub mod output;
pub mod patcher;
pub mod polars_dataset_loader;
pub mod polars_ext;
pub mod prefetch;
pub mod pretokenize;
pub mod quantization;
pub mod reference_sources;
pub mod sidecar;
pub mod tokenizer;

/// Build-time information (git hash, build time, features).
/// Generated by the `built` crate during compilation.
pub mod built_info {
    include!(concat!(env!("OUT_DIR"), "/built.rs"));
}

/// Fused CubeCL operations for optimized GPU kernels.
/// 
/// **Enabled by default** - provides 1.2-1.6x speedups for:
/// - Entropy calculation (fused softmax + reduction)
/// - RMS Norm (fused mean + normalize)
/// - L2 Norm (fused squared sum + sqrt)
/// - Softmax (fused max + exp + sum)
/// - SiLU Gate (fused sigmoid + multiply)
/// - Coherence Score (element-wise fusion)
/// 
/// Disable with `--no-default-features` if needed.
#[cfg(feature = "fused-entropy")]
pub mod fused_ops;
